# 项目相关配置

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8188
  servlet:
    # 应用的访问路径
    context-path: /serviceA/
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.znkj.property: debug
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 5

# Spring配置
spring:
  # MBean 重复加载处理
  jmx:
    default-domain: hjf-property
  main:
    allow-bean-definition-overriding: true
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: druid
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  200MB
      # 设置总上传的文件大小
      max-request-size:  200MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  redis:
#    host: 47.95.122.58
    host: 127.0.0.1
    port: 6379
    password:
#    password:
    shiroredis: 127.0.0.1:6379
    lettuce:
      pool:
        max-active: 30
        max-wait: 1000
        max-idle: 30
        min-idle: 10
    timeout: 1000
    keyPrefix: vean  #Redis key 前缀
    run: true  #Redis是否启动
    listFlush: true   #list记录根据添加修改删除自动清除
    expireTime: 900     #缓存有效时间15分钟
    expireTimeShiro: 1800     #缓存有效时间30分钟



# MyBatis
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.dubbo.lcn.**.vo
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 加载全局的配置文件
  configLocation: classpath:mybatis-config.xml

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

#跨域访问的域名
#cross:
#  domain: http://dev-master.zgzhongnan.com:8089




# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*


# dubbo配置
dubbo:
  application:
    name: dubbo-serviceA
    qos-port: 22225
    qos-enable: true
    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://192.168.2.143:2181
#    address: zookeeper://192.168.0.178:2181
#  scan:
#    base-packages: com.znkj.property
  metadata-report:
    address: zookeeper://192.168.2.143:2181
  protocol:
    port: 20884
    name: dubbo
#    threads: 500
#    accepts: 1000
  #  多协议模式配置 此时需要在Dubbo的@Service注解配置需要暴露的协议，如果不配置，则暴露所有配置的协议.
#  protocols:
#    dubbo:
#      port: 20881
#      name: dubbo
  provider:
    timeout: 60000
  consumer:
    timeout: 60000
    #快速失败
    cluster: failfast
    check: false

#tx-lcn:
#  client:
#    manager-address: 127.0.0.1:8070
#  logger:
#    enabled: true
